### ISSUE TITLE
xtime argument of plot.qcc() not working as expected

### ISSUE THREAD

**Issue by erblast** [luca-scr/qcc#33] opened 2021-09-27 14:47 UTC
Hello,

I found that the xtime  of plot.qcc() is not working as expected. See the following code examples below.

```
library(qcc)
#> Loading required package: ggplot2
#> Package 'qcc' version 3.0
#> Type 'citation("qcc")' for citing this R package in publications.
data("orangejuice")
q1 <- with(orangejuice, qcc(D[trial], sizes = size[trial], type = "p"))

# shading missing
# plot(q1, xtime = rep(Sys.Date(), sum(orangejuice$trial)) + seq(1, sum(orangejuice$trial)))

# not working with time scale
plot(q1, xtime = rep(Sys.time(), sum(orangejuice$trial)) + seq(1, sum(orangejuice$trial)))
#> Error: Invalid input: date_trans works with objects of class Date only

# works
plot(q1)


data(pistonrings)
diameter <- qccGroups(data = pistonrings, diameter, sample)

q2 <- qcc(diameter[1:25,], type = "xbar",
           newdata = diameter[26:40,])

# works
plot(q2, xtime = rep(Sys.Date(), nrow(diameter)) + seq(1, nrow(diameter)))

# not working with time scale
plot(q2, xtime = rep(Sys.time(), nrow(diameter)) + seq(1, nrow(diameter)))
#> Error: Invalid input: date_trans works with objects of class Date only

# works
plot(q2)


df_oj <- orangejuice

q3 <- qcc(
  df_oj$D[df_oj$trial],
  df_oj$size[df_oj$trial],
  type = "p",
  newdata = df_oj$D[! df_oj$trial],
  newsizes = df_oj$size[! df_oj$trial],
  rules = c(1, 2, 3, 4)
)

# not working with date scale
plot(q3, xtime = rep(Sys.Date(), nrow(df_oj)) + seq(1, nrow(df_oj)))
#> Error in limits.2sigma[df$group, 1]: subscript out of bounds

# not working with time scale
plot(q3, xtime = rep(Sys.time(), nrow(df_oj)) + seq(1, nrow(df_oj)))
#> Error in limits.2sigma[df$group, 1]: subscript out of bounds

# works
plot(q3)
plot(q3, chart.all = FALSE)

# not working with date scale
plot(q3, xtime = rep(Sys.Date(), nrow(df_oj)) + seq(1, nrow(df_oj)), chart.all = FALSE)
#> Error in limits.2sigma[df$group, 1]: subscript out of bounds

# not working with time scale
plot(q3, xtime = rep(Sys.time(), nrow(df_oj)) + seq(1, nrow(df_oj)), chart.all = FALSE)
#> Error in limits.2sigma[df$group, 1]: subscript out of bounds

```

**Comment by luca-scr** [comment] 2021-09-27 15:13
I can confirm the bugs you reported. However, it is impossible to check what you have changed in the code due to spaces removing etc. Can you please indicate me the lines of code you have changed?
BTW, in your code there are stylistic (but also substantive) improvements (which I guess can be transferred to code as well). For instance:
```
rep(Sys.Date(), sum(orangejuice$trial)) + seq(1, sum(orangejuice$trial))
```
is equivalent to
```
Sys.Date() + seq_len(sum(orangejuice$trial))
```
with the latter easier to read and less prone to unexpected sequences. Compare the following:
```
seq(1,0)
seq_len(0)
```

**Comment by erblast** [comment] 2021-09-27 15:20
thanks, let me check your suggestion, I will see if I can improve the changes, and leave the whitespace alone

**Closed** 2021-09-28 06:34 UTC
